# Generated by Django 3.1.5 on 2021-01-26 02:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('date_donated', models.DateTimeField(default=django.utils.timezone.now)),
                ('donor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='im.donation')),
            ],
        ),
    ]
