# Generated by Django 3.1.5 on 2021-01-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_auto_20210126_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='donation',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.CharField(default='item', max_length=50),
        ),
    ]
