# Generated by Django 3.1.5 on 2021-02-03 08:32

from django.db import migrations, models
import django.utils.timezone
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_auto_20210126_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapDonation',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(db_column='modifyTimestamp', editable=False)),
                ('item', models.CharField(db_column='itemName', max_length=50)),
                ('quantity', models.IntegerField(db_column='itemQuantity', default=0)),
                ('description', models.TextField(db_column='itemDescription')),
                ('date_donated', models.DateTimeField(db_column='dateDonation', default=django.utils.timezone.now)),
                ('donor', models.CharField(db_column='donorName', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LdapInventory',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(db_column='modifyTimestamp', editable=False)),
                ('item', models.CharField(db_column='itemName', default='item', max_length=50)),
                ('quantity', models.IntegerField(db_column='itemQuantity', default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
